### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'events'

### ISSUE THREAD

**Issue by ltfschoen** [ltfschoen/SecretPath#2]
If I use the custom Relayer in branch 'nunya' of this repo, and then using this PR https://github.com/svub/nunya/pull/33 run `yarn run:submitRequestValue`, the custom Gateway.sol that is deployed on Localsecret processes a transaction using its `send` function, then this Relayer broadcasts it to the custom Secret Gateway and onto the `requestValue` function of the custom Secret contract, which returns a result associated with a task id in the post execution of the custom Secret Gateway. This custom Relayer parses events in its `parse_event_from_txn` function. An example of the `transaction_result` is shown below. 

<details>
  <summary>Click here to view: Transaction result RAW with error message</summary>
  
  ```
2024-12-25 02:50:45,904 [SCRT Interface: INFO] Transaction result: TxInfo(height=881, txhash='D6AED0461DA60683DA86B7408BE8506D66E509C4A25C5836501311A2E32841FC', rawlog='', logs=[{'msg': 0, 'type': 'message', 'key': 'action', 'value': '/secret.compute.v1beta1.MsgExecuteContract'}, {'msg': 0, 'type': 'message', 'key': 'sender', 'value': 'secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg'}, {'msg': 0, 'type': 'message', 'key': 'module', 'value': 'compute'}, {'msg': 0, 'type': 'message', 'key': 'contract_address', 'value': 'secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q'}, {'msg': 0, 'type': 'execute', 'key': 'contract_address', 'value': 'secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q'}, {'msg': 0, 'type': 'wasm', 'key': 'contract_address', 'value': 'secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q'}, {'msg': 0, 'type': 'wasm', 'key': 'task_id', 'value': '4'}, {'msg': 0, 'type': 'wasm', 'key': 'status', 'value': 'sent to private contract'}, {'msg': 0, 'type': 'execute', 'key': 'contract_address', 'value': 'secret1gyruqan6yxf0q423t8z5zce3x7np35uw8s8wqc'}, {'msg': 0, 'type': 'wasm', 'key': 'contract_address', 'value': 'secret1gyruqan6yxf0q423t8z5zce3x7np35uw8s8wqc'}, {'msg': 0, 'type': 'wasm', 'key': 't709WEDLevOai28Z3yfCMZSBecnlsUtDscfMT8uZoD/UfK4xGo+3l8gfMUWZ+kL4tnfJD2DDdKxOq3Dye+IvHI7bSyI8+/PEJ72YisF8fRecbVPawRWD2KriC218SAxpmEJAp7FAxXURD83IcY8/N16Q7zqub8SXqXBk2tG+csO32bkeNqBr9yh7aDHgGsYAzNTMDFR96IR2TLrsQk9e0T1dFOEUE5VBN+WLHNTu2EbOVhVQ57Jubsv+oTNN+p7EBOq0EYTCLT9dUFF07yNdT2TsJwrWGDTsgzg35ieHdyPYmycbVm/4nSTr3LkaJjFiihz7QqKJNYPLTa6g+AkUDcfxYqfSV7KnB0mPQfBTRDk=', 'value': '9x4wmCWOXoa5zLuPFL/WEozAZPicOZX6/xRRkbrNbBcveOZLLqJ0oBbnhQW7DlIDO8TgeiPuAAor5jQS099O3uw+FaPtToiyn2zjDfnpHoyf1DiyE/n0mG3SGpYGtcQgLeOA8ioHzlLp0GbtMsE0rcCdDxDgvI2hMScgQ0Szji0LnRnXgkkfiC7j1xs9Xhi+Hw3SG++I7DU6QcX6U+I+6cKT7hei3pdyEHuLzcVhvaYaVq8gIKAazDeZLKldn7STLiTUDD1PT8xxggK4fXQoaP/E59zjsSqy7VI0jFPDmmxxk6i3qCUNwJZrInkCxu8HLYTEMTcwShw12PFqve46DKbG3p42IBmgqs4iAHl6Wwk='}, {'msg': 0, 'type': 'wasm', 'key': 'callback_address', 'value': '0xe7f1725e7734ce288f8367e1bb143e90bb3f0512'}, {'msg': 0, 'type': 'wasm', 'key': 'callback_gas_limit', 'value': '0x01c9c380'}, {'msg': 0, 'type': 'wasm', 'key': 'callback_selector', 'value': '0x0f7af612'}, {'msg': 0, 'type': 'wasm', 'key': 'packet_hash', 'value': '0x0518be3f4486eebc099b2a33f7ce26077c15f577ddfacce8fb5b854d400aa3a5'}, {'msg': 0, 'type': 'wasm', 'key': 'packet_signature', 'value': '0x192640c80356877bc11eddc6801ba79bfd0ac9cdacdb765b1e7d6b4bc34af05f1801e0215fdb38cd3e8d505fba611d904b137b3cbf0197f9c9ffcd44b3f236e11b'}, {'msg': 0, 'type': 'wasm', 'key': 'payload_hash', 'value': '0x9e43fe9040e60c956176509d8b9ff5acab35b8f6adf4f526bcc4e919c308add2'}, {'msg': 0, 'type': 'wasm', 'key': 'result', 'value': '0x7b225f726571756573745f6964223a7b226e6574776f726b223a223331333337222c227461736b5f6964223a2234227d2c225f6b6579223a5b37382c38352c37382c38392c36355d2c225f636f6465223a302c225f6e756e79615f627573696e6573735f636f6e74726163745f61646472657373223a22307841464646333131383231433346334146383633433731303342423137424443314261303436303344227d'}, {'msg': 0, 'type': 'wasm', 'key': 'source_network', 'value': 'secretdev-1'}, {'msg': 0, 'type': 'wasm', 'key': 'task_destination_network', 'value': '31337'}], events=[{'type': 'coin_spent', 'attributes': [{'key': 'spender', 'value': 'secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg', 'index': True}, {'key': 'amount', 'value': '300000uscrt', 'index': True}]}, {'type': 'coin_received', 'attributes': [{'key': 'receiver', 'value': 'secret17xpfvakm2amg962yls6f84z3kell8c5ljuhfkp', 'index': True}, {'key': 'amount', 'value': '300000uscrt', 'index': True}]}, {'type': 'transfer', 'attributes': [{'key': 'recipient', 'value': 'secret17xpfvakm2amg962yls6f84z3kell8c5ljuhfkp', 'index': True}, {'key': 'sender', 'value': 'secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg', 'index': True}, {'key': 'amount', 'value': '300000uscrt', 'index': True}]}, {'type': 'message', 'attributes': [{'key': 'sender', 'value': 'secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg', 'index': True}]}, {'type': 'tx', 'attributes': [{'key': 'fee', 'value': '300000uscrt', 'index': True}, {'key': 'fee_payer', 'value': 'secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg', 'index': True}]}, {'type': 'tx', 'attributes': [{'key': 'acc_seq', 'value': 'secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg/3', 'index': True}]}, {'type': 'tx', 'attributes': [{'key': 'signature', 'value': 'JK8W0mpvdYhLct84VGWXarH4ethykLNyfxRn8XrqHmcYL//hMckPbywrdCUP5BQ31b+7CFp+rOgku/HiMgOfHA==', 'index': True}]}, {'type': 'message', 'attributes': [{'key': 'action', 'value': '/secret.compute.v1beta1.MsgExecuteContract', 'index': True}, {'key': 'sender', 'value': 'secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg', 'index': True}, {'key': 'msg_index', 'value': '0', 'index': True}]}, {'type': 'message', 'attributes': [{'key': 'module', 'value': 'compute', 'index': True}, {'key': 'sender', 'value': 'secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg', 'index': True}, {'key': 'contract_address', 'value': 'secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q', 'index': True}, {'key': 'msg_index', 'value': '0', 'index': True}]}, {'type': 'execute', 'attributes': [{'key': 'contract_address', 'value': 'secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q', 'index': True}, {'key': 'msg_index', 'value': '0', 'index': True}]}, {'type': 'wasm', 'attributes': [{'key': 'contract_address', 'value': 'secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q', 'index': True}, {'key': 'task_id', 'value': '4', 'index': True}, {'key': 'status', 'value': 'sent to private contract', 'index': True}, {'key': 'msg_index', 'value': '0', 'index': True}]}, {'type': 'execute', 'attributes': [{'key': 'contract_address', 'value': 'secret1gyruqan6yxf0q423t8z5zce3x7np35uw8s8wqc', 'index': True}, {'key': 'msg_index', 'value': '0', 'index': True}]}, {'type': 'wasm', 'attributes': [{'key': 'contract_address', 'value': 'secret1gyruqan6yxf0q423t8z5zce3x7np35uw8s8wqc', 'index': True}, {'key': 't709WEDLevOai28Z3yfCMZSBecnlsUtDscfMT8uZoD/UfK4xGo+3l8gfMUWZ+kL4tnfJD2DDdKxOq3Dye+IvHI7bSyI8+/PEJ72YisF8fRecbVPawRWD2KriC218SAxpmEJAp7FAxXURD83IcY8/N16Q7zqub8SXqXBk2tG+csO32bkeNqBr9yh7aDHgGsYAzNTMDFR96IR2TLrsQk9e0T1dFOEUE5VBN+WLHNTu2EbOVhVQ57Jubsv+oTNN+p7EBOq0EYTCLT9dUFF07yNdT2TsJwrWGDTsgzg35ieHdyPYmycbVm/4nSTr3LkaJjFiihz7QqKJNYPLTa6g+AkUDcfxYqfSV7KnB0mPQfBTRDk=', 'value': '9x4wmCWOXoa5zLuPFL/WEozAZPicOZX6/xRRkbrNbBcveOZLLqJ0oBbnhQW7DlIDO8TgeiPuAAor5jQS099O3uw+FaPtToiyn2zjDfnpHoyf1DiyE/n0mG3SGpYGtcQgLeOA8ioHzlLp0GbtMsE0rcCdDxDgvI2hMScgQ0Szji0LnRnXgkkfiC7j1xs9Xhi+Hw3SG++I7DU6QcX6U+I+6cKT7hei3pdyEHuLzcVhvaYaVq8gIKAazDeZLKldn7STLiTUDD1PT8xxggK4fXQoaP/E59zjsSqy7VI0jFPDmmxxk6i3qCUNwJZrInkCxu8HLYTEMTcwShw12PFqve46DKbG3p42IBmgqs4iAHl6Wwk=', 'index': True}, {'key': 'msg_index', 'value': '0', 'index': True}]}, {'type': 'execute', 'attributes': [{'key': 'contract_address', 'value': 'secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q', 'index': True}, {'key': 'msg_index', 'value': '0', 'index': True}]}, {'type': 'wasm', 'attributes': [{'key': 'callback_address', 'value': '0xe7f1725e7734ce288f8367e1bb143e90bb3f0512', 'index': True}, {'key': 'callback_gas_limit', 'value': '0x01c9c380', 'index': True}, {'key': 'callback_selector', 'value': '0x0f7af612', 'index': True}, {'key': 'contract_address', 'value': 'secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q', 'index': True}, {'key': 'packet_hash', 'value': '0x0518be3f4486eebc099b2a33f7ce26077c15f577ddfacce8fb5b854d400aa3a5', 'index': True}, {'key': 'packet_signature', 'value': '0x192640c80356877bc11eddc6801ba79bfd0ac9cdacdb765b1e7d6b4bc34af05f1801e0215fdb38cd3e8d505fba611d904b137b3cbf0197f9c9ffcd44b3f236e11b', 'index': True}, {'key': 'payload_hash', 'value': '0x9e43fe9040e60c956176509d8b9ff5acab35b8f6adf4f526bcc4e919c308add2', 'index': True}, {'key': 'result', 'value': '0x7b225f726571756573745f6964223a7b226e6574776f726b223a223331333337222c227461736b5f6964223a2234227d2c225f6b6579223a5b37382c38352c37382c38392c36355d2c225f636f6465223a302c225f6e756e79615f627573696e6573735f636f6e74726163745f61646472657373223a22307841464646333131383231433346334146383633433731303342423137424443314261303436303344227d', 'index': True}, {'key': 'source_network', 'value': 'secretdev-1', 'index': True}, {'key': 'task_destination_network', 'value': '31337', 'index': True}, {'key': 'task_id', 'value': '4', 'index': True}, {'key': 'msg_index', 'value': '0', 'index': True}]}], gas_wanted=3000000, gas_used=131383, tx=Tx(body=TxBody(messages=[MsgExecuteContract(sender='secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg', contract='secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q', msg='{"input":{"inputs":{"task_id":"4","source_network":"31337","user_address":"0x5FbDB2315678afecb367f032d93F642f64180aa3","routing_info":"secret1gyruqan6yxf0q423t8z5zce3x7np35uw8s8wqc","payload_hash":"nkP+kEDmDJVhdlCdi5/1rKs1uPat9PUmvMTpGcMIrdI=","user_key":"A4MYU1tUEF1Keq5gwI/EX5aHGBtP38YlvRp1P6c5f+11","user_pubkey":"BIMYU1tUEF1Keq5gwI/EX5aHGBtP38YlvRp1P6c5f+11NUfxHKhpZkby86ywjjEBavrCPmMMXRH1n2H+9XsNKqU=","routing_code_hash":"0e1904c8f258b365d24865041ab51de62fdbf515d15e8fe785774662201c809a","handle":"request_value","nonce":"AAAAAAAAAAAAAAAL","callback_gas_limit":30000000,"payload":"vlNpd9dOwrQw9lDWa8MdMujeXGJoJeOrtHp0ZDBrWUKp1EdBSlvckUtcbCWiYDvq2dzm8zjNY9INCEDNNA0pth9pUDBTwdJTYbuHaGnWyQHDv3sOoV/wvDpydbkV/bCP59bYhX8PNu5Gebla12fniMJ3NH3O4r0UWVVTfff0bAJ0KuzAaVGWMZueGuElfCeuk9FD1F37j7RcjQHNPxxYjf1V/g5Jjzvi9ublacqFZWamMs4l3XY0fagIoogdpdkVoPQp3mZX0F+sLUsB3ASRZRBAeRYtD57/8geprigUcXKl/c4ccwre0If6b7YZ4N24nFr8lRuu6cXeQaalmoy18wIdoAD/XThmDEEH42MXOCIaVIFyLc8dfHzZ9YrjzN4Qu6Ih8hO/6U2t6FwwM52k+7jVnJb9pJd9k/4P1JhTQRyhaaPQ3OxjrZI7SLoQE1slxVbksXGcEyCipDaM/I1XaRetqQv/t5LL2s7uhNexs/b9tHBd8IqV1/ZaLu2g68mJqqtk51rv3jBSQqKB8AQ9WDblwOspbEls0n8o2X2SYVBgxgXem7Jwyqc=","payload_signature":"xUS1bqdon4M0POm3pkaKWxWOiqV4rdFKMb0fWyB1S7Fju5ZRBQL29tUizh+ij3FWS/mjuEBDii7IXQDvWAeUvg=="}}}', sent_funds=Coins(), code_hash='', encryption_utils=<secret_sdk.util.encrypt_utils.EncryptionUtils object at 0x7bcc8ba79310>)], memo='', timeout_height=0), auth_info=AuthInfo(signer_infos=[SignerInfo(public_key=SimplePublicKey(key=b'\x03\x82\xbe3"M\x9c\xd7\x1d\xb7\xbf\x12\x9d\xc8\xe1\x02\xb2\xd66p\xd1\x1d\xaadd[\x1e\x9a9\x9f\xf7\xfe\xc0'), mode_info=ModeInfo(single=ModeInfoSingle(mode=<SignMode.SIGN_MODE_DIRECT: 1>), multi=None), sequence=3)], fee=Fee(gas_limit=3000000, amount=Coins('300000uscrt'), payer='', granter='')), signatures=[b'$\xaf\x16\xd2jou\x88Kr\xdf8Te\x97j\xb1\xf8z\xd8r\x90\xb3r\x7f\x14g\xf1z\xea\x1eg\x18/\xff\xe11\xc9\x0fo,+t%\x0f\xe4\x147\xd5\xbf\xbb\x08Z~\xac\xe8$\xbb\xf1\xe22\x03\x9f\x1c']), timestamp='2024-12-25T02:50:39Z', code=0, codespace=None, tx_bytes=None, data=[])
Exception in thread Thread-136 (_thread_func):
Traceback (most recent call last):
  File "/root/miniconda3/envs/secretpath_env/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/secretpath_env/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/root/ltfschoen/SecretPath/TNLS-Relayers/relayer.py", line 204, in _thread_func
    self.route_transaction(task)
  File "/root/ltfschoen/SecretPath/TNLS-Relayers/relayer.py", line 181, in route_transaction
    new_tasks, _ = contract_for_txn.call_function(function_name, str(task))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ltfschoen/SecretPath/TNLS-Relayers/scrt_interface.py", line 360, in call_function
    task_list = self.parse_event_from_txn('wasm', logs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ltfschoen/SecretPath/TNLS-Relayers/scrt_interface.py", line 376, in parse_event_from_txn
    events = [event for event in log.events if event['type'] == event_name]
                                 ^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'events'
  ```
</details>

<details>
  <summary>Click here to view: Transaction result (in JSON, custom)</summary>
  
  ```
{
  "TxInfo": {
    "logs": [
      {
        "msg": 0,
        "type": "message",
        "key": "action",
        "value": "/secret.compute.v1beta1.MsgExecuteContract"
      },
      {
        "msg": 0,
        "type": "message",
        "key": "sender",
        "value": "secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg"
      },
      {
        "msg": 0,
        "type": "message",
        "key": "module",
        "value": "compute"
      },
      {
        "msg": 0,
        "type": "message",
        "key": "contract_address",
        "value": "secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q"
      },
      {
        "msg": 0,
        "type": "execute",
        "key": "contract_address",
        "value": "secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q"
      },
      {
        "msg": 0,
        "type": "wasm",
        "key": "contract_address",
        "value": "secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q"
      },
      {
        "msg": 0,
        "type": "wasm",
        "key": "task_id",
        "value": "3"
      },
      {
        "msg": 0,
        "type": "wasm",
        "key": "status",
        "value": "sent to private contract"
      },
      {
        "msg": 0,
        "type": "execute",
        "key": "contract_address",
        "value": "secret1gyruqan6yxf0q423t8z5zce3x7np35uw8s8wqc"
      },
      {
        "msg": 0,
        "type": "wasm",
        "key": "B+XB/beVo08rD3tMAIe+NXvsLsfTIXWvmtVyOudBvTdeKoBR3VdrnYpXETY8o16R/fGypWE6+OsA2mfo4SdeDaUABk6yO/tVM8FMxJiuAY+xrOf8LCFnjcAY7L3ANgZZk5cd9L12ARFvCBrQ3MP+Rlnd9QqsjWEjCMjLs3nE5jzNTIflTtlqktYBeWbAaNODRNgVJgiR2L87B6HQLdMJ1qurOgzUpo9sZM3kfikffuCwjeXDWyuHznbQ68hfRK2bIyCbAStnjw61UnSTyeXf4T4v/uZuy4s8Bqn2dJXOVRaX8jmx9F9KtDPmM4UIrkVnKwvxWTfibGuw7jVJVytEZNntFxPJaFkfIUdv5F31xVU=",
        "value": "i0e2Hrc8ELjMbNhf6Aazt9RIG4P/p1gZL3fts08JXaVZjmz2mMRTGTJ0kQ5U6F56QjKvD3B981fe2F9XxKkMiaDEPGbP5KX7Z93BOe8qGHm56LecuNA2yarMtXM1iyvV/lFMHTwpGuZiyeCQ5cIs+lZ+j4/Vp8NzhX5MoOSAEGvQSzWbZm+SZZphDSwG79c9r3ZqUIYPXZ7J+QMdZSDaQbWikag1Kua/LBBWu1BSHNqkEUmdgqJqsHamd8UnfidvPDSxUurEwZB48EEVm4tMUEuoz675xAa3leAP6R7wZie56tkrK5OgbGSPRcAgmqbRVl1BhGKg7LIH56DNcbb6HLwHlq2oAJtgfg0mqLeqDPc="
      },
      {
        "msg": 0,
        "type": "wasm",
        "key": "contract_address",
        "value": "secret1gyruqan6yxf0q423t8z5zce3x7np35uw8s8wqc"
      },
      {
        "msg": 0,
        "type": "wasm",
        "key": "callback_address",
        "value": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512"
      },
      {
        "msg": 0,
        "type": "wasm",
        "key": "callback_gas_limit",
        "value": "0x01c9c380"
      },
      {
        "msg": 0,
        "type": "wasm",
        "key": "callback_selector",
        "value": "0x0f7af612"
      },
      {
        "msg": 0,
        "type": "wasm",
        "key": "packet_hash",
        "value": "0xfa629fe75fa1ef362d7b938e644f28a148238e08ae6a3e90e1948f465390165a"
      },
      {
        "msg": 0,
        "type": "wasm",
        "key": "packet_signature",
        "value": "0x2fddb9ee4ea9206aa274a930a280bd066463fba494f377c82f8e6d8dc2a7f4d63b33a0ec9d2d33e9aa646e04cd49f3fbaed3b067f8c84725fa07f6ebee838a371c"
      },
      {
        "msg": 0,
        "type": "wasm",
        "key": "payload_hash",
        "value": "0xc3a98212d3a7781b4207f42d6b98572da71d0dd3a40e2818f6fbf15b199ff93f"
      },
      {
        "msg": 0,
        "type": "wasm",
        "key": "result",
        "value": "0x7b225f726571756573745f6964223a7b226e6574776f726b223a223331333337222c227461736b5f6964223a2233227d2c225f6b6579223a5b37382c38352c37382c38392c36355d2c225f636f6465223a302c225f6e756e79615f627573696e6573735f636f6e74726163745f61646472657373223a22307841464646333131383231433346334146383633433731303342423137424443314261303436303344227d"
      },
      {
        "msg": 0,
        "type": "wasm",
        "key": "source_network",
        "value": "secretdev-1"
      },
      {
        "msg": 0,
        "type": "wasm",
        "key": "task_destination_network",
        "value": "31337"
      }
    ],
    "events": [
      {
        "type": "coin_spent",
        "attributes": [
          {
            "key": "spender",
            "value": "secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg",
            "index": "true"
          },
          {
            "key": "amount",
            "value": "300000uscrt",
            "index": "true"
          }
        ]
      },
      {
        "type": "coin_received",
        "attributes": [
          {
            "key": "receiver",
            "value": "secret17xpfvakm2amg962yls6f84z3kell8c5ljuhfkp",
            "index": "true"
          },
          {
            "key": "amount",
            "value": "300000uscrt",
            "index": "true"
          }
        ]
      },
      {
        "type": "transfer",
        "attributes": [
          {
            "key": "recipient",
            "value": "secret17xpfvakm2amg962yls6f84z3kell8c5ljuhfkp",
            "index": "true"
          },
          {
            "key": "sender",
            "value": "secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg",
            "index": "true"
          },
          {
            "key": "amount",
            "value": "300000uscrt",
            "index": "true"
          }
        ]
      },
      {
        "type": "message",
        "attributes": [
          {
            "key": "sender",
            "value": "secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg",
            "index": "true"
          }
        ]
      },
      {
        "type": "tx",
        "attributes": [
          {
            "key": "fee",
            "value": "300000uscrt",
            "index": "true"
          },
          {
            "key": "fee_payer",
            "value": "secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg",
            "index": "true"
          }
        ]
      },
      {
        "type": "tx",
        "attributes": [
          {
            "key": "acc_seq",
            "value": "secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg/2",
            "index": "true"
          }
        ]
      },
      {
        "type": "tx",
        "attributes": [
          {
            "key": "signature",
            "value": "1FgeaO84Mx3dZwEv4mSGo5ZlO7+HYSbUWncOoHxwciwp1cYYBzT/yUqamc9Cl8LVeNhxfEFrmHudVNUppM80rA==",
            "index": "true"
          }
        ]
      },
      {
        "type": "message",
        "attributes": [
          {
            "key": "action",
            "value": "/secret.compute.v1beta1.MsgExecuteContract",
            "index": "true"
          },
          {
            "key": "sender",
            "value": "secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg",
            "index": "true"
          },
          {
            "key": "msg_index",
            "value": "0",
            "index": "true"
          }
        ]
      },
      {
        "type": "message",
        "attributes": [
          {
            "key": "module",
            "value": "compute",
            "index": "true"
          },
          {
            "key": "sender",
            "value": "secret1glfedwlusunwly7q05umghzwl6nf2vj6wr38fg",
            "index": "true"
          },
          {
            "key": "contract_address",
            "value": "secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q",
            "index": "true"
          },
          {
            "key": "msg_index",
            "value": "0",
            "index": "true"
          }
        ]
      },
      {
        "type": "execute",
        "attributes": [
          {
            "key": "contract_address",
            "value": "secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q",
            "index": "true"
          },
          {
            "key": "msg_index",
            "value": "0",
            "index": "true"
          }
        ]
      },
      {
        "type": "wasm",
        "attributes": [
          {
            "key": "contract_address",
            "value": "secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q",
            "index": "true"
          },
          {
            "key": "task_id",
            "value": "3",
            "index": "true"
          },
          {
            "key": "status",
            "value": "sent to private contract",
            "index": "true"
          },
          {
            "key": "msg_index",
            "value": "0",
            "index": "true"
          }
        ]
      },
      {
        "type": "execute",
        "attributes": [
          {
            "key": "contract_address",
            "value": "secret1gyruqan6yxf0q423t8z5zce3x7np35uw8s8wqc",
            "index": "true"
          },
          {
            "key": "msg_index",
            "value": "0",
            "index": "true"
          }
        ]
      },
      {
        "type": "wasm",
        "attributes": [
          {
            "key": "B+XB/beVo08rD3tMAIe+NXvsLsfTIXWvmtVyOudBvTdeKoBR3VdrnYpXETY8o16R/fGypWE6+OsA2mfo4SdeDaUABk6yO/tVM8FMxJiuAY+xrOf8LCFnjcAY7L3ANgZZk5cd9L12ARFvCBrQ3MP+Rlnd9QqsjWEjCMjLs3nE5jzNTIflTtlqktYBeWbAaNODRNgVJgiR2L87B6HQLdMJ1qurOgzUpo9sZM3kfikffuCwjeXDWyuHznbQ68hfRK2bIyCbAStnjw61UnSTyeXf4T4v/uZuy4s8Bqn2dJXOVRaX8jmx9F9KtDPmM4UIrkVnKwvxWTfibGuw7jVJVytEZNntFxPJaFkfIUdv5F31xVU=",
            "value": "i0e2Hrc8ELjMbNhf6Aazt9RIG4P/p1gZL3fts08JXaVZjmz2mMRTGTJ0kQ5U6F56QjKvD3B981fe2F9XxKkMiaDEPGbP5KX7Z93BOe8qGHm56LecuNA2yarMtXM1iyvV/lFMHTwpGuZiyeCQ5cIs+lZ+j4/Vp8NzhX5MoOSAEGvQSzWbZm+SZZphDSwG79c9r3ZqUIYPXZ7J+QMdZSDaQbWikag1Kua/LBBWu1BSHNqkEUmdgqJqsHamd8UnfidvPDSxUurEwZB48EEVm4tMUEuoz675xAa3leAP6R7wZie56tkrK5OgbGSPRcAgmqbRVl1BhGKg7LIH56DNcbb6HLwHlq2oAJtgfg0mqLeqDPc=",
            "index": "true"
          },
          {
            "key": "contract_address",
            "value": "secret1gyruqan6yxf0q423t8z5zce3x7np35uw8s8wqc",
            "index": "true"
          },
          {
            "key": "msg_index",
            "value": "0",
            "index": "true"
          }
        ]
      },
      {
        "type": "execute",
        "attributes": [
          {
            "key": "contract_address",
            "value": "secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q",
            "index": "true"
          },
          {
            "key": "msg_index",
            "value": "0",
            "index": "true"
          }
        ]
      },
      {
        "type": "wasm",
        "attributes": [
          {
            "key": "callback_address",
            "value": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
            "index": "true"
          },
          {
            "key": "callback_gas_limit",
            "value": "0x01c9c380",
            "index": "true"
          },
          {
            "key": "callback_selector",
            "value": "0x0f7af612",
            "index": "true"
          },
          {
            "key": "contract_address",
            "value": "secret1mfk7n6mc2cg6lznujmeckdh4x0a5ezf6hx6y8q",
            "index": "true"
          },
          {
            "key": "packet_hash",
            "value": "0xfa629fe75fa1ef362d7b938e644f28a148238e08ae6a3e90e1948f465390165a",
            "index": "true"
          },
          {
            "key": "packet_signature",
            "value": "0x2fddb9ee4ea9206aa274a930a280bd066463fba494f377c82f8e6d8dc2a7f4d63b33a0ec9d2d33e9aa646e04cd49f3fbaed3b067f8c84725fa07f6ebee838a371c",
            "index": "true"
          },
          {
            "key": "payload_hash",
            "value": "0xc3a98212d3a7781b4207f42d6b98572da71d0dd3a40e2818f6fbf15b199ff93f",
            "index": "true"
          },
          {
            "key": "result",
            "value": "0x7b225f726571756573745f6964223a7b226e6574776f726b223a223331333337222c227461736b5f6964223a2233227d2c225f6b6579223a5b37382c38352c37382c38392c36355d2c225f636f6465223a302c225f6e756e79615f627573696e6573735f636f6e74726163745f61646472657373223a22307841464646333131383231433346334146383633433731303342423137424443314261303436303344227d",
            "index": "true"
          },
          {
            "key": "source_network",
            "value": "secretdev-1",
            "index": "true"
          },
          {
            "key": "task_destination_network",
            "value": "31337",
            "index": "true"
          },
          {
            "key": "task_id",
            "value": "3",
            "index": "true"
          },
          {
            "key": "msg_index",
            "value": "0",
            "index": "true"
          }
        ]
      }
    ]
  }
}
  ```
</details>

It appears that we'd only be interested in forwarding transactions for tasks that have `task.task_data` with a key `task_id`, and those that have events under the `events` list where there is actually a `task_destination_network` that has been specified. The `logs` list does not have any relevant events.

**Comment by ltfschoen** [comment]
Closing since fixed in commit [33ca8d4](https://github.com/ltfschoen/SecretPath/commit/33ca8d401a4fa8f55b06b5017adbabbbf8604b4b)
